export const characters = [
    { name: 'Klee', 
    element: 'Pyro', 
    weapon: 'Catalyst', 
    rarity: 5, 
    image: '/images/chars/Klee.png' 
    },
    
    { name: 'Keqing', element: 'Electro', weapon: 'Sword', rarity: 5, image: '/images/chars/Keqing.png' },
    { name: 'Kazuha', element: 'Anemo', weapon: 'Sword', rarity: 5, image: '/images/chars/Kazuha.png' },
    { name: 'Kaeya', element: 'Cryo', weapon: 'Sword', rarity: 4, image: '/images/chars/Kaeya.png' },
    { name: 'Jean', element: 'Anemo', weapon: 'Sword', rarity: 5, image: '/images/chars/Jean.png' },
    { name: 'Itto', element: 'Geo', weapon: 'Claymore', rarity: 5, image: '/images/chars/Itto.png' },
    { name: 'Hu Tao', element: 'Pyro', weapon: 'Polearm', rarity: 5, image: '/images/chars/Hutao.png' },
    { name: 'Heizou', element: 'Anemo', weapon: 'Catalyst', rarity: 4, image: '/images/chars/Heizou.png' },
    { name: 'Gorou', element: 'Geo', weapon: 'Bow', rarity: 4, image: '/images/chars/Gorou.png' },
    { name: 'Ganyu', element: 'Cryo', weapon: 'Bow', rarity: 5, image: '/images/chars/Ganyu.png' },
    { name: 'Fischl', element: 'Electro', weapon: 'Bow', rarity: 4, image: '/images/chars/Fischl.png' },
    { name: 'Faruzan', element: 'Pyro', weapon: 'Sword', rarity: 4, image: '/images/chars/Faruzan.png' },
    { name: 'Eula', element: 'Cryo', weapon: 'Claymore', rarity: 5, image: '/images/chars/Eula.png' },
    { name: 'Dori', element: 'Hydro', weapon: 'Sword', rarity: 4, image: '/images/chars/Dori.png' },
    { name: 'Diona', element: 'Cryo', weapon: 'Bow', rarity: 4, image: '/images/chars/Diona.png' },
    { name: 'Diluc', element: 'Pyro', weapon: 'Claymore', rarity: 5, image: '/images/chars/Diluc.png' },
    { name: 'Dehya', element: 'Pyro', weapon: 'Claymore', rarity: 4, image: '/images/chars/Dehya.png' },
    { name: 'Cyno', element: 'Electro', weapon: 'Sword', rarity: 5, image: '/images/chars/Cyno.png' },
    { name: 'Collei', element: 'Dendro', weapon: 'Bow', rarity: 4, image: '/images/chars/Collei.png' },
    { name: 'Chongyun', element: 'Cryo', weapon: 'Claymore', rarity: 4, image: '/images/chars/Chongyun.png' },
    { name: 'Childe', element: 'Hydro', weapon: 'Bow', rarity: 5, image: '/images/chars/Childe.png' },
    { name: 'Candance', element: 'Pyro', weapon: 'Catalyst', rarity: 4, image: '/images/chars/Candance.png' },
    { name: 'Benett', element: 'Pyro', weapon: 'Sword', rarity: 4, image: '/images/chars/Benett.png' },
    { name: 'Beidou', element: 'Electro', weapon: 'Claymore', rarity: 4, image: '/images/chars/Beidou.png' },
    { name: 'Barbara', element: 'Hydro', weapon: 'Catalyst', rarity: 4, image: '/images/chars/Barbara.png' },
    { name: 'Ayato', element: 'Hydro', weapon: 'Sword', rarity: 5, image: '/images/chars/Ayato.png' },
    { name: 'Ayaka', element: 'Cryo', weapon: 'Sword', rarity: 5, image: '/images/chars/Ayaka.png' },
    { name: 'Albedo', element: 'Geo', weapon: 'Sword', rarity: 5, image: '/images/chars/Albedo.png' },
    { name: 'Amber', element: 'Pyro', weapon: 'Bow', rarity: 4, image: '/images/chars/Amber.png' },
    { name: 'Aloy', element: 'Cryo', weapon: 'Bow', rarity: 5, image: '/images/chars/Aloy.png' },
    { name: 'Baizhu', element: 'Dendro', weapon: 'Catalyst', rarity: 5, image: '/images/chars/Baizhu.png' },
]
